# Generated by Django 4.1.6 on 2023-02-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0004_autor_fecha_creacion_libro_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
